### ISSUE TITLE
make test fails from master

### ISSUE THREAD

**Issue by federicohyo** [UCI-CARL/CARLsim4#55] opened 2018-04-23 08:08 UTC
Hi there,

I have an issue while compiling 'make test' with carlsim4.
See the picture below, the error seems related to a new LIF neuron model that is not present in carlsim4...

![error_carlsim4](https://user-images.githubusercontent.com/7521438/39114128-2da99516-46de-11e8-9f41-0106355388fb.png)

any idea how to fix this?

thank you for your good work.
 Federico

**Comment by hkashyap** [comment] 2018-04-24 03:38
We cannot reproduce your issue. LIF neurons are already merged into master, since last year. It is not only LIF neurons, you are also missing other methods such as setIntegrationMethod(...).

My guess is that you are using a old install of CARLsim4 library to build the tests. Make sure your CARLSIM4_INSTALL_DIR points to what you want.

Here is a screenshot of the test suite running using the current master.

![screenshot from 2018-04-23 20-31-32](https://user-images.githubusercontent.com/16297410/39164784-299209e2-4736-11e8-8e01-d2cd3fafedf9.png)

**Closed** 2019-04-05 23:32 UTC
